services:
  lavalink: &lavalink
    profiles:
      - prod
    # noinspection SpellCheckingInspection,SpellCheckingInspection
    image: ghcr.io/lavalink-devs/lavalink:4.1.1-distroless
    container_name: radio_pele_lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx4G
      - SERVER_PORT=2333
      # This is not actually a secret, so whatever. The container is not exposed to the internet.
      - LAVALINK_SERVER_PASSWORD=j^t411l0@xVJy4pg%!0sfDge6bp4bPpS8aT1r&Ipc^Ir^JCx*epMjo$6@2EA
      - PLUGINS_YOUTUBE_OAUTH_REFRESH_TOKEN=$PLUGINS_YOUTUBE_OAUTH_REFRESH_TOKEN
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333
      #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:2333/metrics"]
      #start_period: 10s
      #interval: 10s
      #timeout: 5s
      #retries: 360 # 60min * 60s / 10s = 360 retries for 1hr
  lavalink-local:
    <<: *lavalink
    profiles:
      - local
    container_name: radio_pele_lavalink_local
    ports:
      - "2333:2333"
  bot:
    profiles:
      - prod
    image: us-east1-docker.pkg.dev/flash-bazaar-487/radio-pele/radio-pele-bot:latest
    build: ./bot
    container_name: radio_pele_bot
    restart: unless-stopped
    depends_on:
      - lavalink
    networks:
      - lavalink
networks:
  # Network for Lavalink service; accessible to the bot container
  lavalink:
    name: lavalink
