spring:
  application:
    name: radio-pele
  profiles:
    active: prod
  jmx:
    enabled: false
logging:
  level:
    root: INFO
    com:
      lm_pakkanen:
        radio_pele_java: DEBUG