lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.3"
      snapshot: false
  server:
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: true
    youtubePlaylistLoadLimit: 1 # Number of pages, 100 videos per page
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    timeouts:
      connectTimeoutMs: 3000
      connectionRequestTimeoutMs: 3000
      socketTimeoutMs: 3000
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - WEB
      - MWEB
      - WEBEMBEDDED
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
metrics:
  prometheus:
    enabled: true
    endpoint: /metrics
logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: true
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
