lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.3"
      snapshot: false
  server:
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: true
      vimeo: false
      nico: false
      http: false
      local: false
    youtubePlaylistLoadLimit: 1 # Number of pages, 100 videos per page
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    bufferDurationMs: 10000
    frameBufferDurationMs: 5000
    trackStuckThresholdMs: 10000
    opusEncodingQuality: 0
    resamplingQuality: LOW
    playerUpdateInterval: 10
    gc-warnings: false
    timeouts:
      connectTimeoutMs: 3000
      connectionRequestTimeoutMs: 3000
      socketTimeoutMs: 3000
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - WEBEMBEDDED
      - ANDROID_VR
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
logging:
  level:
    root: INFO
    lavalink: INFO
    lavalink.server.io.SocketContext: INFO
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: INFO
    dev.lavalink.youtube: INFO
  request:
    enabled: false
    includeClientInfo: true
    includeHeaders: true
    includeQueryString: true
    includePayload: true
