lavalink:
  plugins:
    # https://github.com/lavalink-devs/youtube-source/releases
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
  server:
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      nico: false
      http: false
      local: false
    filters:
      volume: false
      equalizer: false
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false
    youtubePlaylistLoadLimit: 1 # Number of pages, 100 videos per page
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    bufferDurationMs: 400
    frameBufferDurationMs: 2000
    trackStuckThresholdMs: 25000
    opusEncodingQuality: 5
    resamplingQuality: LOW
    playerUpdateInterval: 5
    gc-warnings: true
    timeouts:
      connectTimeoutMs: 3000
      connectionRequestTimeoutMs: 3000
      socketTimeoutMs: 3000
plugins:
  youtube:
    remoteCipher:
      url: "https://cipher.kikkia.dev/"
    enabled: true
    oauth:
      enabled: true
      skipInitialization: false
      refreshToken: REPLACE_ME
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      # See https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients
      #- TV # Requires login
      #- TVHTML5EMBEDDED # Requires login
      - WEBEMBEDDED
      - MWEB
      - WEB
      - ANDROID_VR
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
logging:
  level:
    root: INFO
    lavalink: INFO
    lavalink.server.io.SocketContext: INFO
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: INFO
    dev.lavalink.youtube: INFO
  request:
    enabled: false               # Disabled to reduce I/O overhead and CPU usage on small instance
    includeClientInfo: false
    includeHeaders: false
    includeQueryString: false
    includePayload: false
